name       : shards
version    : 0.17.3
release    : 1
source     :
    - https://github.com/crystal-lang/shards/archive/refs/tags/v0.17.3.tar.gz : 6512ff51bd69057f4da4783eb6b14c29d9a88b97d35985356d1dc644a08424c7
homepage   : https://crystal-lang.org
license    : Apache-2.0
component  : programming
summary    : Dependency manager for the Crystal language
description: |
     Shards is the dependency manager for the Crystal programming language.
networking : yes
builddeps  :
    - pkgconfig(yaml-0.1)
    - crystal
    - fossil
    - git
    - mercurial
build      : |
    %make release=1
install    : |
    %make_install PREFIX=/usr
check      : |
    %make test_unit
    %make test_integration
